name: solid_compare_img
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  http: ^1.2.2
  image: ^3.3.0
  provider: ^6.1.2
  solid_lints: ^0.1.5
  validator_regex: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
